//Keys are the color names, values are ('foreground color:background color:foreground bright/dark', 'NAME')
const METAL_COLORS = {
    'silver1': ['7:7:1', 'SILVER'],
    'silver2': ['7:3:0', 'SILVER'],
    'gray': ['0:7:1', 'GRAY'],
    'taupe_gray1': ['0:7:1', 'TAUPE_GRAY'],
    'taupe_gray2': ['7:3:0', 'TAUPE_GRAY'],
    'white1': ['3:7:0', 'WHITE'],
    'black1': ['0:7:0', 'BLACK'],
    'brass': ['6:6:1', 'BRASS'],
    'gold': ['6:6:1', 'GOLD'],
    'copper': ['6:4:0', 'COPPER'],
    'bronze': ['6:4:0', 'BRONZE'],
    'white2': ['7:7:1', 'WHITE'],
    'ochre': ['6:6:1', 'OCHRE'],
    'pale_brown': ['7:3:0', 'PALE_BROWN'],
    'black2': ['5:6:0', 'BLACK'],
    'tan': ['6:6:1', 'TAN'],
    'heliotrope': ['5:5:1', 'HELIOTROPE'],
    'pink': ['5:5:1', 'PINK'],
    'pale_blue': ['3:7:0', 'PALE_BLUE'],
    'red_purple': ['4:5:0', 'RED_PURPLE']
};

//Alloy colors
const ALLOY_COLORS = {
  "silver1": {
    "silver1": 10.0, 
    "silver2": 5.0,
    "gray": 5.0,
    "taupe_gray1": 5.0,
    "taupe_gray2": 5.0,
    "white1": 1.0, 
    "black1": 0.1,
    "brass": 0.1,
    "gold": 0.1, 
    "copper": 0.1,
    "bronze": 0.1, 
    "white2": 1.0, 
    "ochre": 0.1,
    "pale_brown": 0.1,
    "black2": 0.1,
    "tan": 0.1,
    "heliotrope": 0.0,
    "pink": 0.0,
    "pale_blue": 0.0, 
    "red_purple": 0.0},
  "silver2": {
    "silver1": 5.0,
    "silver2": 10.0,
    "gray": 5.0,
    "taupe_gray1": 5.0,
    "taupe_gray2": 5.0, 
    "white1": 1.0, 
    "black1": 0.1, 
    "brass": 0.1, 
    "gold": 0.1,
    "copper": 0.1,
    "bronze": 0.1, 
    "white2": 1.0,
    "ochre": 0.1, 
    "pale_brown": 0.1,
    "black2": 0.1,
    "tan": 0.1,
    "heliotrope": 0.0, 
    "pink": 0.0, 
    "pale_blue": 0.0,
    "red_purple": 0.0}, 
  "gray": {
    "silver1": 5.0, 
    "silver2": 5.0,
    "gray": 10.0,
    "taupe_gray1": 5.0, 
    "taupe_gray2": 5.0, 
    "white1": 1.0, 
    "black1": 0.1,
    "brass": 0.1,
    "gold": 0.1,
    "copper": 0.1,
    "bronze": 0.1,
    "white2": 1.0,
    "ochre": 0.1, 
    "pale_brown": 0.1, 
    "black2": 0.1,
    "tan": 0.1,
    "heliotrope": 0.0, 
    "pink": 0.0,
    "pale_blue": 0.0,
    "red_purple": 0.0},
  "taupe_gray1": {
    "silver1": 1.0,
    "silver2": 1.0,
    "gray": 5.0,
    "taupe_gray1": 10.0,
    "taupe_gray2": 5.0, 
    "white1": 1.0, 
    "black1": 0.1, 
    "brass": 0.1,
    "gold": 0.1,
    "copper": 0.1, 
    "bronze": 0.1, 
    "white2": 1.0, 
    "ochre": 0.1, 
    "pale_brown": 0.1,
    "black2": 0.1,
    "tan": 0.1,
    "heliotrope": 0.0, 
    "pink": 0.0, 
    "pale_blue": 0.0, 
    "red_purple": 0.0},
  "taupe_gray2": {
    "silver1": 1.0,
    "silver2": 1.0,
    "gray": 1.0,
    "taupe_gray1": 5.0,
    "taupe_gray2": 10.0,
    "white1": 1.0,
    "black1": 0.1,
    "brass": 0.1,
    "gold": 0.1,
    "copper": 0.1,
    "bronze": 0.1,
    "white2": 1.0, 
    "ochre": 0.1,
    "pale_brown": 0.1, 
    "black2": 0.1, 
    "tan": 0.1, 
    "heliotrope": 0.0,
    "pink": 0.0, 
    "pale_blue": 0.0,
    "red_purple": 0.0},
  "white1": {
    "silver1": 3.0,
    "silver2": 3.0, 
    "gray": 3.0, 
    "taupe_gray1": 3.0, 
    "taupe_gray2": 3.0,
    "white1": 10.0,
    "black1": 0.1, 
    "brass": 0.1, 
    "gold": 0.1,
    "copper": 0.1,
    "bronze": 0.1,
    "white2": 1.0,
    "ochre": 0.1, 
    "pale_brown": 0.1,
    "black2": 0.1,
    "tan": 0.1,
    "heliotrope": 0.0,
    "pink": 0.0,
    "pale_blue": 0.0,
    "red_purple": 0.0},
  "black1": {
    "silver1": 2.0,
    "silver2": 2.0,
    "gray": 2.0,
    "taupe_gray1": 2.0,
    "taupe_gray2": 2.0, 
    "white1": 2.0,
    "black1": 10.0,
    "brass": 0.1,
    "gold": 0.1,
    "copper": 0.1, 
    "bronze": 0.1, 
    "white2": 2.0, 
    "ochre": 0.1, 
    "pale_brown": 0.1, 
    "black2": 0.1,
    "tan": 0.1,
    "heliotrope": 0.0,
    "pink": 0.0, 
    "pale_blue": 0.0, 
    "red_purple": 0.0},
  "brass": {
    "silver1": 0.1,
    "silver2": 0.1,
    "gray": 0.1,
    "taupe_gray1": 0.1,
    "taupe_gray2": 0.1,
    "white1": 0.1, 
    "black1": 4.0,
    "brass": 10.0,
    "gold": 5.0, 
    "copper": 5.0, 
    "bronze": 5.0, 
    "white2": 0.1,
    "ochre": 4.0, 
    "pale_brown": 0.1, 
    "black2": 0.1,
    "tan": 5.0, 
    "heliotrope": 3.0,
    "pink": 2.0, 
    "pale_blue": 0.0,
    "red_purple": 1.0},
  "gold": {
    "silver1": 0.1, 
    "silver2": 0.1, 
    "gray": 0.1, 
    "taupe_gray1": 0.1, 
    "taupe_gray2": 0.1,
    "white1": 0.1, 
    "black1": 2.0, 
    "brass": 5.0, 
    "gold": 10.0,
    "copper": 5.0,
    "bronze": 5.0,
    "white2": 0.1,
    "ochre": 3.0,
    "pale_brown": 0.1,
    "black2": 0.1, 
    "tan": 5.0,
    "heliotrope": 3.0,
    "pink": 2.0,
    "pale_blue": 0.0, 
    "red_purple": 1.0},
  "copper": {
    "silver1": 0.1,
    "silver2": 0.1,
    "gray": 0.1,
    "taupe_gray1": 0.1,
    "taupe_gray2": 0.1,
    "white1": 0.1,
    "black1": 2.0,
    "brass": 5.0,
    "gold": 5.0, 
    "copper": 10.0,
    "bronze": 5.0, 
    "white2": 0.1, 
    "ochre": 3.0, 
    "pale_brown": 0.1, 
    "black2": 0.1,
    "tan": 5.0, 
    "heliotrope": 3.0, 
    "pink": 2.0, 
    "pale_blue": 0.0,
    "red_purple": 1.0}, 
  "bronze": {
    "silver1": 0.1, 
    "silver2": 0.1, 
    "gray": 0.1,
    "taupe_gray1": 0.1, 
    "taupe_gray2": 0.1, 
    "white1": 0.1,
    "black1": 2.0,
    "brass": 5.0, 
    "gold": 5.0,
    "copper": 5.0, 
    "bronze": 10.0,
    "white2": 0.1,
    "ochre": 4.0,
    "pale_brown": 0.1, 
    "black2": 0.1,
    "tan": 5.0,
    "heliotrope": 3.0, 
    "pink": 1.0,
    "pale_blue": 0.0,
    "red_purple": 1.0}, 
  "white2": {
    "silver1": 5.0, 
    "silver2": 5.0,
    "gray": 3.0,
    "taupe_gray1": 3.0,
    "taupe_gray2": 3.0,
    "white1": 5.0, 
    "black1": 0.0,
    "brass": 3.0, 
    "gold": 1.0,
    "copper": 1.0,
    "bronze": 2.0,
    "white2": 10.0,
    "ochre": 2.0,
    "pale_brown": 4.0, 
    "black2": 0.0, 
    "tan": 0.5, 
    "heliotrope": 0.2,
    "pink": 0.1,
    "pale_blue": 0.3, 
    "red_purple": 0.1},
  "ochre": {
    "silver1": 0.1, 
    "silver2": 0.1, 
    "gray": 0.1,
    "taupe_gray1": 0.1,
    "taupe_gray2": 0.1,
    "white1": 0.0,
    "black1": 0.0,
    "brass": 3.0, 
    "gold": 2.0, 
    "copper": 3.0,
    "bronze": 3.0, 
    "white2": 0.0, 
    "ochre": 10.0, 
    "pale_brown": 5.0,
    "black2": 0.1, 
    "tan": 1.0, 
    "heliotrope": 0.1, 
    "pink": 0.1, 
    "pale_blue": 0.0,
    "red_purple": 0.1},
  "pale_brown": {
    "silver1": 0.0,
    "silver2": 0.0,
    "gray": 2.0, 
    "taupe_gray1": 2.0,
    "taupe_gray2": 2.0,
    "white1": 0.0, 
    "black1": 3.0,
    "brass": 1.0, 
    "gold": 0.5,
    "copper": 1.0,
    "bronze": 1.0,
    "white2": 0.0, 
    "ochre": 5.0,
    "pale_brown": 10.0,
    "black2": 0.0, 
    "tan": 3.0, 
    "heliotrope": 0.0,
    "pink": 0.0, 
    "pale_blue": 0.0, 
    "red_purple": 0.0},
  "black2": {
    "silver1": 2.0, 
    "silver2": 2.0, 
    "gray": 5.0,
    "taupe_gray1": 4.0,
    "taupe_gray2": 4.0,
    "white1": 0.3,
    "black1": 5.0, 
    "brass": 1.0,
    "gold": 0.1,
    "copper": 1.0, 
    "bronze": 0.1, 
    "white2": 0.0, 
    "ochre": 0.5,
    "pale_brown": 0.1,
    "black2": 10.0,
    "tan": 0.5,
    "heliotrope": 0.0,
    "pink": 0.0,
    "pale_blue": 0.0,
    "red_purple": 0.0},
  "tan": {
    "silver1": 0.0, 
    "silver2": 0.0,
    "gray": 0.1, 
    "taupe_gray1": 0.5,
    "taupe_gray2": 0.5,
    "white1": 0.0,
    "black1": 2.0, 
    "brass": 3.0, 
    "gold": 2.0,
    "copper": 3.0,
    "bronze": 3.0, 
    "white2": 0.0,
    "ochre": 5.0, 
    "pale_brown": 4.0,
    "black2": 2.0,
    "tan": 10.0,
    "heliotrope": 0.2, 
    "pink": 0.0,
    "pale_blue": 0.0, 
    "red_purple": 0.0},
  "heliotrope": {
    "silver1": 0.1,
    "silver2": 0.1,
    "gray": 0.1,
    "taupe_gray1": 0.1,
    "taupe_gray2": 0.1,
    "white1": 0.0,
    "black1": 0.0,
    "brass": 3.0,
    "gold": 1.0,
    "copper": 2.0,
    "bronze": 3.0,
    "white2": 0.0,
    "ochre": 2.0, 
    "pale_brown": 1.0,
    "black2": 0.0,
    "tan": 2.0, 
    "heliotrope": 10.0, 
    "pink": 5.0, 
    "pale_blue": 0.0, 
    "red_purple": 1.0},
  "pink": {
    "silver1": 0.1,
    "silver2": 0.1,
    "gray": 0.1, 
    "taupe_gray1": 0.1, 
    "taupe_gray2": 0.1, 
    "white1": 0.0, 
    "black1": 0.0, 
    "brass": 3.0, 
    "gold": 1.0,
    "copper": 2.0, 
    "bronze": 3.0,
    "white2": 0.0,
    "ochre": 2.0, 
    "pale_brown": 1.0,
    "black2": 0.0,
    "tan": 2.0, 
    "heliotrope": 5.0,
    "pink": 10.0,
    "pale_blue": 0.0,
    "red_purple": 1.0},
  "pale_blue": {
    "silver1": 3, 
    "silver2": 3,
    "gray": 2,
    "taupe_gray1": 2, 
    "taupe_gray2": 2,
    "white1": 0,
    "black1": 0,
    "brass": 0,
    "gold": 0,
    "copper": 0,
    "bronze": 0,
    "white2": 0,
    "ochre": 0, 
    "pale_brown": 0, 
    "black2": 0,
    "tan": 0,
    "heliotrope": 0,
    "pink": 0, 
    "pale_blue": 10,
    "red_purple": 0},
  "red_purple": {
    "silver1": 0.0,
    "silver2": 0.0,
    "gray": 0.0, 
    "taupe_gray1": 0.0, 
    "taupe_gray2": 0.0,
    "white1": 0.0, 
    "black1": 0.0, 
    "brass": 2.0,
    "gold": 0.0,
    "copper": 2.0, 
    "bronze": 2.0, 
    "white2": 0.0, 
    "ochre": 1.0, 
    "pale_brown": 1.0,
    "black2": 0.0,
    "tan": 1.0,
    "heliotrope": 0.5,
    "pink": 0.5, 
    "pale_blue": 0.0, 
    "red_purple": 10.0}
  };
  
// Metal color probabilities
const basic_colors = {'gray': 3,
                'silver1': 1,
                'silver2': 1,
                'taupe_gray1': 1,
                'taupe_gray2': 1,
                'white1': 0.3,
                'black1': 0.5
                };

const fancy_colors = {'brass': 1,
                'gold': 1,
                'copper': 1,
                'bronze': 1,
                'white2': 4,
                'ochre': 1,
                'pale_brown': 1,
                'black2': 1,
                'tan': 1,
                'silver2': 4
                }

const rare_colors = {'heliotrope': 1,
               'pink': 1,
               'pale_blue': 1,
               'red_purple': 1}  ;
               
const BASIC_COLORS = Object.keys(basic_colors);
const BASIC_COLOR_PROBS = normalize(Object.values(basic_colors));
const FANCY_COLORS = Object.keys(fancy_colors);
const FANCY_COLOR_PROBS = normalize(Object.values(fancy_colors));
const RARE_COLORS = Object.keys(rare_colors);
const RARE_COLORS_PROBS = normalize(Object.values(rare_colors));

// Ore colors
// Each pair is ('foreground color:background color:foreground bright/dark', probability weight)
let ore_colors = [
    ['4:7:0', 1],
    ['6:7:1', 1],
    ['2:7:1', 1],
    ['2:7:0', 1],
    ['7:7:1', 1],
    ['0:7:1', 1],
    ['6:7:0', 1],
    ['1:7:1', 1],
    ['0:7:1', 1]
  ]

ore_colors = unzip(ore_colors);
const ORE_COLORS = ore_colors[0];
const ORE_COLOR_PROBS = normalize(ore_colors[1]);


function pickOreColor() {
  //Return a randomly selected ore color string.
  return randomChoice(ORE_COLORS, ORE_COLOR_PROBS)[0];
}

function pickMetalColor(rarity) {
  //Return the randomly selected color specification strings for a metal.
  let pick;
  if (rarity === 'basic') {
    pick = randomChoice(BASIC_COLORS, BASIC_COLOR_PROBS)[0];
  } else if (rarity === 'fancy') {
    pick = randomChoice(FANCY_COLORS, FANCY_COLOR_PROBS)[0];
  } else {
    pick = randomChoice(RARE_COLORS, RARE_COLORS_PROBS)[0];
  }
  let pick_values = METAL_COLORS[pick];
  return [pick, pick_values[0], pick_values[1]];
}

function pickAlloyColor(primary_metal_color) {
  //Return the randomly selected color specification string for an alloy.
  let picking_dict = ALLOY_COLORS[primary_metal_color];
  let pick = randomChoice(Object.keys(picking_dict), normalize(Object.values(picking_dict)))[0];
  return [pick, METAL_COLORS[pick][0], METAL_COLORS[pick][1]];
}

