function load_vanilla_metals() {
  /** Add the vanilla metals to VANILLA_METALS so that they can be used for alloys.
  */
 
  metals_to_add = [{
    'name': 'copper',
    'advanced': false,
    'usable': true,
    'allow_from_ores': true,
    'constituent_metals': [],
    'color_name': 'copper',
    'ores': ['Native copper (1)', 'Malachite (1)', 'Tetrahedrite (1)'],
    'aesthetic_value': 8,
    'material_properties': {
      'DISPLAY_COLOR': '6:6:1',
      'BUILD_COLOR': '6:6:1',
      'MATERIAL_VALUE': 2,
      'SPEC_HEAT': 385,
      'MELTING_POINT': 11952,
      'BOILING_POINT': 14611,
      'SOLID_DENSITY': 8930,
      'LIQUID_DENSITY': 8020,
      'MOLAR_MASS': 63546,
      'IMPACT_YIELD':245000,
      'IMPACT_FRACTURE':770000,
      'IMPACT_STRAIN_AT_YIELD':175,
      'COMPRESSIVE_YIELD':245000,
      'COMPRESSIVE_FRACTURE':770000,
      'COMPRESSIVE_STRAIN_AT_YIELD':175,
      'TENSILE_YIELD':70000,
      'TENSILE_FRACTURE':220000,
      'TENSILE_STRAIN_AT_YIELD':58,
      'TORSION_YIELD':70000,
      'TORSION_FRACTURE':220000,
      'TORSION_STRAIN_AT_YIELD':145,
      'SHEAR_YIELD':70000,
      'SHEAR_FRACTURE':220000,
      'SHEAR_STRAIN_AT_YIELD':145,
      'BENDING_YIELD':70000,
      'BENDING_FRACTURE':220000,
      'BENDING_STRAIN_AT_YIELD':58,
      'MAX_EDGE':10000,
      'STATE_COLOR': {'ALL_SOLID': 'COPPER'}
    }
  },
  {
    'name': 'iron',
    'advanced': false,
    'usable': true,
    'allow_from_ores': true,
    'constituent_metals': [],
    'color_name': 'gray',
    'ores': ['Hematite (1)', 'Magnetite (1)', 'Limonite (1)'],
    'aesthetic_value': 2,
    'material_properties': {
        'BUILD_COLOR':'0:7:1',
        'MATERIAL_VALUE':10,
        'SPEC_HEAT':450,
        'MELTING_POINT':12768,
        'BOILING_POINT':15150,
        'SOLID_DENSITY':7850,
        'LIQUID_DENSITY':6980,
        'MOLAR_MASS':55845,
        'IMPACT_YIELD':542500,
        'IMPACT_FRACTURE':1085000,
        'IMPACT_STRAIN_AT_YIELD':319,
        'COMPRESSIVE_YIELD':542500,
        'COMPRESSIVE_FRACTURE':1085000,
        'COMPRESSIVE_STRAIN_AT_YIELD':319,
        'TENSILE_YIELD':155000,
        'TENSILE_FRACTURE':310000,
        'TENSILE_STRAIN_AT_YIELD':73,
        'TORSION_YIELD':155000,
        'TORSION_FRACTURE':310000,
        'TORSION_STRAIN_AT_YIELD':189,
        'SHEAR_YIELD':155000,
        'SHEAR_FRACTURE':310000,
        'SHEAR_STRAIN_AT_YIELD':189,
        'BENDING_YIELD':155000,
        'BENDING_FRACTURE':310000,
        'BENDING_STRAIN_AT_YIELD':73,
        'MAX_EDGE':10000,
        'STATE_COLOR': {'ALL_SOLID':'GRAY'}
    }
  },
  {
    'name': 'gold',
    'advanced': false,
    'usable': true,
    'allow_from_ores': true,
    'constituent_metals': [],
    'color_name': 'gold',
    'ores': ['Native gold (1)'],
    'aesthetic_value': 30,
    'material_properties': {
        'BUILD_COLOR':'6:6:1',
        'MATERIAL_VALUE':30,
        'SPEC_HEAT':129,
        'MELTING_POINT': 11915,
        'BOILING_POINT': 15141,
        'SOLID_DENSITY': 19320,
        'LIQUID_DENSITY': 17310,
        'MOLAR_MASS': 196967,
        'IMPACT_YIELD': 175000,
        'IMPACT_FRACTURE': 350000,
        'IMPACT_STRAIN_AT_YIELD': 97,
        'COMPRESSIVE_YIELD': 175000,
        'COMPRESSIVE_FRACTURE': 350000,
        'COMPRESSIVE_STRAIN_AT_YIELD': 97,
        'TENSILE_YIELD': 50000,
        'TENSILE_FRACTURE': 100000,
        'TENSILE_STRAIN_AT_YIELD': 64,
        'TORSION_YIELD': 50000,
        'TORSION_FRACTURE': 100000,
        'TORSION_STRAIN_AT_YIELD': 185,
        'SHEAR_YIELD': 50000,
        'SHEAR_FRACTURE': 100000,
        'SHEAR_STRAIN_AT_YIELD': 185,
        'BENDING_YIELD': 50000,
        'BENDING_FRACTURE': 100000,
        'BENDING_STRAIN_AT_YIELD': 64,
        'MAX_EDGE': 10000,
        'STATE_COLOR': {'ALL_SOLID':'GOLD'}
    }
  },
  {
    'name': 'silver',
    'advanced': false,
    'usable': true,
    'allow_from_ores': true,
    'constituent_metals': [],
    'color_name': 'silver1',
    'ores': ['Horn silver (1)', 'native Silver (1)', 'Tetrahedrite (0.2)', 'Galena (0.5)'],
    'aesthetic_value': 10,
    'material_properties': {
        'BUILD_COLOR':'7:7:1',
        'MATERIAL_VALUE':10,
        'SPEC_HEAT':230,
      	'SOLID_DENSITY': 10490,
        'LIQUID_DENSITY': 9320,
        'MOLAR_MASS': 107868,
        'IMPACT_YIELD': 350000,
        'IMPACT_FRACTURE': 595000,
        'IMPACT_STRAIN_AT_YIELD': 350,
        'COMPRESSIVE_YIELD': 350000,
        'COMPRESSIVE_FRACTURE': 595000,
        'COMPRESSIVE_STRAIN_AT_YIELD': 350,
        'TENSILE_YIELD': 100000,
        'TENSILE_FRACTURE': 170000,
        'TENSILE_STRAIN_AT_YIELD': 120,
        'TORSION_YIELD': 100000,
        'TORSION_FRACTURE': 170000,
        'TORSION_STRAIN_AT_YIELD': 333,
        'SHEAR_YIELD': 100000,
        'SHEAR_FRACTURE': 170000,
        'SHEAR_STRAIN_AT_YIELD': 333,
        'BENDING_YIELD': 100000,
        'BENDING_FRACTURE': 170000,
        'BENDING_STRAIN_AT_YIELD': 120,
        'MAX_EDGE': 10000,
        'STATE_COLOR': {'ALL_SOLID':'SILVER'}
    }
  },
  {
    'name': 'nickel',
    'advanced': false,
    'usable': true,
    'allow_from_ores': true,
    'constituent_metals': [],
    'color_name': 'silver2',
    'ores': ['Garnierite (1)'],
    'aesthetic_value': 8,
    'material_properties': {
      	'BUILD_COLOR': '7:3:0',
        'MATERIAL_VALUE': 2,
        'SPEC_HEAT': 444,
        'MELTING_POINT': 12619,
        'BOILING_POINT': 15243,
        'SOLID_DENSITY': 8800,
        'LIQUID_DENSITY': 7810,
        'MOLAR_MASS': 58693,
        'IMPACT_YIELD': 70000,
        'IMPACT_FRACTURE': 560000,
        'IMPACT_STRAIN_AT_YIELD': 39,
        'COMPRESSIVE_YIELD': 70000,
        'COMPRESSIVE_FRACTURE': 560000,
        'COMPRESSIVE_STRAIN_AT_YIELD': 39,
        'TENSILE_YIELD': 20000,
        'TENSILE_FRACTURE': 160000,
        'TENSILE_STRAIN_AT_YIELD': 10,
        'TORSION_YIELD': 20000,
        'TORSION_FRACTURE': 160000,
        'TORSION_STRAIN_AT_YIELD': 26,
        'SHEAR_YIELD': 20000,
        'SHEAR_FRACTURE': 160000,
        'SHEAR_STRAIN_AT_YIELD': 26,
        'BENDING_YIELD': 20000,
        'BENDING_FRACTURE': 160000,
        'BENDING_STRAIN_AT_YIELD': 10,
        'MAX_EDGE': 10000,
        'STATE_COLOR': {'ALL_SOLID': 'SILVER'}
    }
  },
  {
  'name': 'zinc',
  'advanced': false,
  'usable': true,
  'allow_from_ores': true,
  'constituent_metals': [],
  'color_name': 'silver2',
  'ores': ['Sphalerite (1)'],
  'aesthetic_value': 2,
  'material_properties': {
    	'DISPLAY_COLOR': '7:3:0',
      'BUILD_COLOR': '7:3:0',
      'MATERIAL_VALUE': 2,
      'SPEC_HEAT': 390,
      'MELTING_POINT': 10755,
      'BOILING_POINT': 11633,
      'SOLID_DENSITY': 7135,
      'LIQUID_DENSITY': 6570,
      'MOLAR_MASS': 65380,
      'IMPACT_YIELD': 175000,
      'IMPACT_FRACTURE': 525000,
      'IMPACT_STRAIN_AT_YIELD': 250,
      'COMPRESSIVE_YIELD': 175000,
      'COMPRESSIVE_FRACTURE': 525000,
      'COMPRESSIVE_STRAIN_AT_YIELD': 250,
      'TENSILE_YIELD': 50000,
      'TENSILE_FRACTURE': 150000,
      'TENSILE_STRAIN_AT_YIELD': 46,
      'TORSION_YIELD': 50000,
      'TORSION_FRACTURE': 150000,
      'TORSION_STRAIN_AT_YIELD': 116,
      'SHEAR_YIELD': 50000,
      'SHEAR_FRACTURE': 150000,
      'SHEAR_STRAIN_AT_YIELD': 116,
      'BENDING_YIELD': 50000,
      'BENDING_FRACTURE': 150000,
      'BENDING_STRAIN_AT_YIELD': 46,
      'MAX_EDGE': 10000,
      'STATE_COLOR': {'ALL_SOLID': 'SILVER'}
    }
  },
  {
    'name': 'bronze',
    'advanced': false,
    'usable': true,
    'allow_from_ores': true,
    'constituent_metals': [['tin', 1], ['copper', 1]],
    'color_name': 'bronze',
    'aesthetic_value': 5,
    'material_properties': {
      	'BUILD_COLOR': '6:4:0',
        'MATERIAL_VALUE': 5,
        'SPEC_HEAT': 435,
        'MELTING_POINT': 11868,
        'BOILING_POINT': 14140,
        'SOLID_DENSITY': 8250,
        'LIQUID_DENSITY': 8020,
        'MOLAR_MASS': 80000,
        'IMPACT_YIELD': 602000,
        'IMPACT_FRACTURE': 843500,
        'IMPACT_STRAIN_AT_YIELD': 547,
        'COMPRESSIVE_YIELD': 602000,
        'COMPRESSIVE_FRACTURE': 843500,
        'COMPRESSIVE_STRAIN_AT_YIELD': 547,
        'TENSILE_YIELD': 172000,
        'TENSILE_FRACTURE': 241000,
        'TENSILE_STRAIN_AT_YIELD': 156,
        'TORSION_YIELD': 172000,
        'TORSION_FRACTURE': 241000,
        'TORSION_STRAIN_AT_YIELD': 156,
        'SHEAR_YIELD': 172000,
        'SHEAR_FRACTURE': 241000,
        'SHEAR_STRAIN_AT_YIELD': 156,
        'BENDING_YIELD': 172000,
        'BENDING_FRACTURE': 241000,
        'BENDING_STRAIN_AT_YIELD': 156,
        'MAX_EDGE': 10000,
        'STATE_COLOR': {'ALL_SOLID': 'BRONZE'}
  }
  },
  {
    'name': 'brass',
    'advanced': false,
    'usable': true,
    'allow_from_ores': true,
    'constituent_metals': [['zinc', 1], ['copper', 1]],
    'color_name': 'brass',
    'aesthetic_value': 5,
    'material_properties': {
      	'BUILD_COLOR': '6:6:1',
        'MATERIAL_VALUE': 7,
        'SPEC_HEAT': 377,
        'MELTING_POINT': 11656,
        'BOILING_POINT': 14068,
        'SOLID_DENSITY': 8550,
        'LIQUID_DENSITY': 8000,
        'MOLAR_MASS': 64000,
        'IMPACT_YIELD': 290500,
        'IMPACT_FRACTURE': 1015000,
        'IMPACT_STRAIN_AT_YIELD': 264,
        'COMPRESSIVE_YIELD': 290500,
        'COMPRESSIVE_FRACTURE': 1015000,
        'COMPRESSIVE_STRAIN_AT_YIELD': 264,
        'TENSILE_YIELD': 83000,
        'TENSILE_FRACTURE': 290000,
        'TENSILE_STRAIN_AT_YIELD': 75,
        'TORSION_YIELD': 83000,
        'TORSION_FRACTURE': 299000,
        'TORSION_STRAIN_AT_YIELD': 75,
        'SHEAR_YIELD': 83000,
        'SHEAR_FRACTURE': 290000,
        'SHEAR_STRAIN_AT_YIELD': 75,
        'BENDING_YIELD': 83000,
        'BENDING_FRACTURE': 290000,
        'BENDING_STRAIN_AT_YIELD': 75,
        'MAX_EDGE': 10000,
        'STATE_COLOR': {'ALL_SOLID': 'BRASS'}
    }
  },
  {
    'name': 'platinum',
    'advanced': false,
    'usable': true,
    'allow_from_ores': true,
    'constituent_metals': [],
    'color_name': 'silver2',
    'ores': ['Native platinum (1)'],
    'aesthetic_value': 40,
    'material_properties': {
      	'BUILD_COLOR': '7:7:1',
        'MATERIAL_VALUE': 40,
        'SPEC_HEAT': 130,
        'MELTING_POINT': 13182,
        'BOILING_POINT': 16885,
        'SOLID_DENSITY': 21400,
        'LIQUID_DENSITY': 19770,
        'MOLAR_MASS': 195084,
        'IMPACT_YIELD': 350000,
        'IMPACT_FRACTURE': 700000,
        'IMPACT_STRAIN_AT_YIELD': 152,
        'COMPRESSIVE_YIELD': 350000,
        'COMPRESSIVE_FRACTURE': 700000,
        'COMPRESSIVE_STRAIN_AT_YIELD': 152,
        'TENSILE_YIELD': 100000,
        'TENSILE_FRACTURE': 200000,
        'TENSILE_STRAIN_AT_YIELD': 60,
        'TORSION_YIELD': 100000,
        'TORSION_FRACTURE': 200000,
        'TORSION_STRAIN_AT_YIELD': 164,
        'SHEAR_YIELD': 100000,
        'SHEAR_FRACTURE': 200000,
        'SHEAR_STRAIN_AT_YIELD': 164,
        'BENDING_YIELD': 100000,
        'BENDING_FRACTURE': 200000,
        'BENDING_STRAIN_AT_YIELD': 60,
        'MAX_EDGE': 10000,
        'STATE_COLOR': {'ALL_SOLID': 'SILVER'}
    }
  },
  {
    'name': 'electrum',
    'advanced': false,
    'usable': true,
    'allow_from_ores': true,
    'constituent_metals': [['silver', 1], ['gold', 1]],
    'color_name': 'ochre',
    'aesthetic_value': 20,
    'material_properties': {
      	'BUILD_COLOR': '6:6:1',
        'MATERIAL_VALUE': 20,
        'SPEC_HEAT': 180,
        'MELTING_POINT': 11828,
        'BOILING_POINT': 14968,
        'SOLID_DENSITY': 14905,
        'LIQUID_DENSITY': 13000,
        'MOLAR_MASS': 150000,
        'IMPACT_YIELD': 175000,
        'IMPACT_FRACTURE': 350000,
        'IMPACT_STRAIN_AT_YIELD': 97,
        'COMPRESSIVE_YIELD': 175000,
        'COMPRESSIVE_FRACTURE': 350000,
        'COMPRESSIVE_STRAIN_AT_YIELD': 97,
        'TENSILE_YIELD': 50000,
        'TENSILE_FRACTURE': 100000,
        'TENSILE_STRAIN_AT_YIELD': 64,
        'TORSION_YIELD': 50000,
        'TORSION_FRACTURE': 100000,
        'TORSION_STRAIN_AT_YIELD': 185,
        'SHEAR_YIELD': 50000,
        'SHEAR_FRACTURE': 100000,
        'SHEAR_STRAIN_AT_YIELD': 185,
        'BENDING_YIELD': 50000,
        'BENDING_FRACTURE': 100000,
        'BENDING_STRAIN_AT_YIELD': 64,
        'MAX_EDGE': 10000,
        'STATE_COLOR': {'ALL_SOLID': 'OCHRE'}
    }
  },
  {
    'name': 'tin',
    'advanced': false,
    'usable': true,
    'allow_from_ores': true,
    'constituent_metals': [],
    'color_name': 'silver1',
    'ores': ['Cassiterite (1)'],
    'aesthetic_value': 2,
    'material_properties': {
      	'BUILD_COLOR': '7:3:0',
        'MATERIAL_VALUE': 2,
        'SPEC_HEAT': 210,
        'MELTING_POINT': 10417,
        'BOILING_POINT': 14684,
        'SOLID_DENSITY': 7280,
        'LIQUID_DENSITY': 6990,
        'MOLAR_MASS': 118710,
        'IMPACT_YIELD': 42000,
        'IMPACT_FRACTURE': 350000,
        'IMPACT_STRAIN_AT_YIELD': 724,
        'COMPRESSIVE_YIELD': 42000,
        'COMPRESSIVE_FRACTURE': 350000,
        'COMPRESSIVE_STRAIN_AT_YIELD': 724,
        'TENSILE_YIELD': 12000,
        'TENSILE_FRACTURE': 100000,
        'TENSILE_STRAIN_AT_YIELD': 24,
        'TORSION_YIELD': 12000,
        'TORSION_FRACTURE': 100000,
        'TORSION_STRAIN_AT_YIELD': 66,
        'SHEAR_YIELD': 12000,
        'SHEAR_FRACTURE': 100000,
        'SHEAR_STRAIN_AT_YIELD': 66,
        'BENDING_YIELD': 12000,
        'BENDING_FRACTURE': 100000,
        'BENDING_STRAIN_AT_YIELD': 24,
        'MAX_EDGE': 10000,
        'STATE_COLOR': {'ALL_SOLID': 'SILVER'}
    }
  },
  {
    'name': 'trifle pewter',
    'advanced': false,
    'usable': true,
    'allow_from_ores': true,
    'constituent_metals': [['tin', 2], ['copper', 1]],
    'aesthetic_value': 5,
    'color_name': 'taupe_gray2',
    'material_properties': {
      	'BUILD_COLOR': '7:7:1',
        'MATERIAL_VALUE': 5,
        'SPEC_HEAT': 210,
        'MELTING_POINT': 10417,
        'BOILING_POINT': 14684,
        'SOLID_DENSITY': 7280,
        'LIQUID_DENSITY': 6990,
        'MOLAR_MASS': 118710,
        'IMPACT_YIELD': 42000,
        'IMPACT_FRACTURE': 350000,
        'IMPACT_STRAIN_AT_YIELD': 724,
        'COMPRESSIVE_YIELD': 42000,
        'COMPRESSIVE_FRACTURE': 350000,
        'COMPRESSIVE_STRAIN_AT_YIELD': 724,
        'TENSILE_YIELD': 12000,
        'TENSILE_FRACTURE': 100000,
        'TENSILE_STRAIN_AT_YIELD': 24,
        'TORSION_YIELD': 12000,
        'TORSION_FRACTURE': 100000,
        'TORSION_STRAIN_AT_YIELD': 66,
        'SHEAR_YIELD': 12000,
        'SHEAR_FRACTURE': 100000,
        'SHEAR_STRAIN_AT_YIELD': 66,
        'BENDING_YIELD': 12000,
        'BENDING_FRACTURE': 100000,
        'BENDING_STRAIN_AT_YIELD': 24,
        'MAX_EDGE': 10000,
        'STATE_COLOR': {'ALL_SOLID': 'TAUPE_GRAY'}
    }
  },
  {
    'name': 'fine pewter',
    'advanced': false,
    'usable': true,
    'allow_from_ores': true,
    'constituent_metals': [['tin', 3], ['copper', 1]],
    'color_name': 'silver1',
    'aesthetic_value': 10,
    'material_properties': {
        'BUILD_COLOR':'0:7:1',
        'MATERIAL_VALUE':10,
        'SPEC_HEAT':450,
        'MELTING_POINT':12768,
        'BOILING_POINT':15150,
        'SOLID_DENSITY':7850,
        'LIQUID_DENSITY':6980,
        'MOLAR_MASS':55845,
        'IMPACT_YIELD':542500,
        'IMPACT_FRACTURE':1085000,
        'IMPACT_STRAIN_AT_YIELD':319,
        'COMPRESSIVE_YIELD':542500,
        'COMPRESSIVE_FRACTURE':1085000,
        'COMPRESSIVE_STRAIN_AT_YIELD':319,
        'TENSILE_YIELD':155000,
        'TENSILE_FRACTURE':310000,
        'TENSILE_STRAIN_AT_YIELD':73,
        'TORSION_YIELD':155000,
        'TORSION_FRACTURE':310000,
        'TORSION_STRAIN_AT_YIELD':189,
        'SHEAR_YIELD':155000,
        'SHEAR_FRACTURE':310000,
        'SHEAR_STRAIN_AT_YIELD':189,
        'BENDING_YIELD':155000,
        'BENDING_FRACTURE':310000,
        'BENDING_STRAIN_AT_YIELD':73,
        'MAX_EDGE':10000,
        'STATE_COLOR': {'ALL_SOLID':'SILVER'}
    }
  },
  {
    'name': 'lay pewter',
    'advanced': false,
    'usable': true,
    'allow_from_ores': true,
    'constituent_metals': [['tin', 2], ['copper', 1], ['lead', 1]],
    'color_name': 'white1',
    'aesthetic_value': 3,
    'material_properties': {
      	'BUILD_COLOR': '3:7:0',
        'MATERIAL_VALUE': 3,
        'SPEC_HEAT': 210,
        'MELTING_POINT': 10417,
        'BOILING_POINT': 14684,
        'SOLID_DENSITY': 7280,
        'LIQUID_DENSITY': 6990,
        'MOLAR_MASS': 118710,
        'IMPACT_YIELD': 42000,
        'IMPACT_FRACTURE': 350000,
        'IMPACT_STRAIN_AT_YIELD': 724,
        'COMPRESSIVE_YIELD': 42000,
        'COMPRESSIVE_FRACTURE': 350000,
        'COMPRESSIVE_STRAIN_AT_YIELD': 724,
        'TENSILE_YIELD': 12000,
        'TENSILE_FRACTURE': 100000,
        'TENSILE_STRAIN_AT_YIELD': 24,
        'TORSION_YIELD': 12000,
        'TORSION_FRACTURE': 100000,
        'TORSION_STRAIN_AT_YIELD': 66,
        'SHEAR_YIELD': 12000,
        'SHEAR_FRACTURE': 100000,
        'SHEAR_STRAIN_AT_YIELD': 66,
        'BENDING_YIELD': 12000,
        'BENDING_FRACTURE': 100000,
        'BENDING_STRAIN_AT_YIELD': 24,
        'MAX_EDGE': 10000,
        'STATE_COLOR': {'ALL_SOLID':'WHITE'}
    }
  },
  {
    'name': 'lead',
    'advanced': false,
    'usable': true,
    'allow_from_ores': true,
    'constituent_metals': [],
    'color_name': 'taupe_gray1',
    'ores': ['Galena (1)'],
    'aesthetic_value': 2,
    'material_properties': {
      	'BUILD_COLOR': '0:7:1',
        'MATERIAL_VALUE': 2,
        'SPEC_HEAT': 130,
        'MELTING_POINT': 10589,
        'BOILING_POINT': 13148,
        'SOLID_DENSITY': 11340,
        'LIQUID_DENSITY': 10660,
        'MOLAR_MASS': 207200,
        'IMPACT_YIELD': 35000,
        'IMPACT_FRACTURE': 42000,
        'IMPACT_STRAIN_AT_YIELD': 760,
        'COMPRESSIVE_YIELD': 35000,
        'COMPRESSIVE_FRACTURE': 42000,
        'COMPRESSIVE_STRAIN_AT_YIELD': 760,
        'TENSILE_YIELD': 10000,
        'TENSILE_FRACTURE': 12000,
        'TENSILE_STRAIN_AT_YIELD': 63,
        'TORSION_YIELD': 10000,
        'TORSION_FRACTURE': 12000,
        'TORSION_STRAIN_AT_YIELD': 179,
        'SHEAR_YIELD': 10000,
        'SHEAR_FRACTURE': 12000,
        'SHEAR_STRAIN_AT_YIELD': 179,
        'BENDING_YIELD': 10000,
        'BENDING_FRACTURE': 12000,
        'BENDING_STRAIN_AT_YIELD': 63,
        'MAX_EDGE': 10000,
        'STATE_COLOR': {'ALL_SOLID':'TAUPE_GRAY'}
    }
  },
  {
    'name': 'aluminum',
    'advanced': false,
    'usable': true,
    'allow_from_ores': true,
    'constituent_metals': [],
    'color_name': 'white2',
    'ores': ['Native aluminum (1)'],
    'aesthetic_value': 40,
    'material_properties': {
      	'BUILD_COLOR': '7:7:1',
        'MATERIAL_VALUE': 40,
        'SPEC_HEAT': 900,
        'MELTING_POINT': 11188,
        'BOILING_POINT': 14534,
        'SOLID_DENSITY': 2700,
        'LIQUID_DENSITY': 2375,
        'MOLAR_MASS': 26981,
        'IMPACT_YIELD': 70000,
        'IMPACT_FRACTURE': 175000,
        'IMPACT_STRAIN_AT_YIELD': 921,
        'COMPRESSIVE_YIELD': 70000,
        'COMPRESSIVE_FRACTURE': 175000,
        'COMPRESSIVE_STRAIN_AT_YIELD': 921,
        'TENSILE_YIELD': 20000,
        'TENSILE_FRACTURE': 50000,
        'TENSILE_STRAIN_AT_YIELD': 29,
        'TORSION_YIELD': 20000,
        'TORSION_FRACTURE': 50000,
        'TORSION_STRAIN_AT_YIELD': 77,
        'SHEAR_YIELD': 20000,
        'SHEAR_FRACTURE': 50000,
        'SHEAR_STRAIN_AT_YIELD': 77,
        'BENDING_YIELD': 20000,
        'BENDING_FRACTURE': 50000,
        'BENDING_STRAIN_AT_YIELD': 29,
        'MAX_EDGE': 10000,
        'STATE_COLOR': {'ALL_SOLID':'WHITE'}
    }
  },
  {
    'name': 'nickel silver',
    'advanced': false,
    'usable': true,
    'allow_from_ores': true,
    'constituent_metals': [['nickel', 2], ['copper', 1], ['zinc', 1]],
    'color_name': 'silver1',
    'aesthetic_value': 3,
    'material_properties': {
      	'BUILD_COLOR': '7:7:1',
        'MATERIAL_VALUE': 3,
        'SPEC_HEAT': 444,
        'MELTING_POINT': 11620,
        'BOILING_POINT': 15243,
        'SOLID_DENSITY': 8650,
        'LIQUID_DENSITY': 7810,
        'MOLAR_MASS': 58693,
        'IMPACT_YIELD': 70000,
        'IMPACT_FRACTURE': 560000,
        'IMPACT_STRAIN_AT_YIELD': 388,
        'COMPRESSIVE_YIELD': 70000,
        'COMPRESSIVE_FRACTURE': 560000,
        'COMPRESSIVE_STRAIN_AT_YIELD': 388,
        'TENSILE_YIELD': 20000,
        'TENSILE_FRACTURE': 160000,
        'TENSILE_STRAIN_AT_YIELD': 10,
        'TORSION_YIELD': 20000,
        'TORSION_FRACTURE': 160000,
        'TORSION_STRAIN_AT_YIELD': 26,
        'SHEAR_YIELD': 20000,
        'SHEAR_FRACTURE': 160000,
        'SHEAR_STRAIN_AT_YIELD': 26,
        'BENDING_YIELD': 20000,
        'BENDING_FRACTURE': 160000,
        'BENDING_STRAIN_AT_YIELD': 10,
        'MAX_EDGE': 10000,
        'STATE_COLOR': {'ALL_SOLID':'SILVER'}
    }
    },
    {
      'name': 'billon',
      'advanced': false,
      'usable': true,
      'allow_from_ores': true,
      'constituent_metals': [['silver', 1], ['copper', 1]],
      'color_name': 'pale_brown',
      'aesthetic_value': 6,
      'material_properties': {
        	'BUILD_COLOR': '7:3:0',
          'MATERIAL_VALUE': 6,
          'SPEC_HEAT': 385,
          'MELTING_POINT': 11952,
          'BOILING_POINT': 14611,
          'SOLID_DENSITY': 8930,
          'LIQUID_DENSITY': 8020,
          'MOLAR_MASS': 63546,
          'IMPACT_YIELD': 245000,
          'IMPACT_FRACTURE': 770000,
          'IMPACT_STRAIN_AT_YIELD': 175,
          'COMPRESSIVE_YIELD': 245000,
          'COMPRESSIVE_FRACTURE': 770000,
          'COMPRESSIVE_STRAIN_AT_YIELD': 175,
          'TENSILE_YIELD': 70000,
          'TENSILE_FRACTURE': 220000,
          'TENSILE_STRAIN_AT_YIELD': 58,
          'TORSION_YIELD': 70000,
          'TORSION_FRACTURE': 220000,
          'TORSION_STRAIN_AT_YIELD': 145,
          'SHEAR_YIELD': 70000,
          'SHEAR_FRACTURE': 220000,
          'SHEAR_STRAIN_AT_YIELD': 145,
          'BENDING_YIELD': 70000,
          'BENDING_FRACTURE': 220000,
          'BENDING_STRAIN_AT_YIELD': 58,
          'MAX_EDGE': 10000,
          'STATE_COLOR': {'ALL_SOLID':'PALE_BROWN'}
      }
    },
    {
      'name': 'sterling silver',
      'advanced': false,
      'usable': true,
      'allow_from_ores': true,
      'constituent_metals': [['silver', 3], ['copper', 1]],
      'color_name': 'white2',
      'aesthetic_value': 8,
      'material_properties': {
        	'BUILD_COLOR': '7:7:1',
          'MATERIAL_VALUE': 8,
          'SPEC_HEAT': 230,
          'MELTING_POINT': 11602,
          'BOILING_POINT': 13892,
          'SOLID_DENSITY': 10490,
          'LIQUID_DENSITY': 9320,
          'MOLAR_MASS': 107868,
          'IMPACT_YIELD': 350000,
          'IMPACT_FRACTURE': 595000,
          'IMPACT_STRAIN_AT_YIELD': 350,
          'COMPRESSIVE_YIELD': 350000,
          'COMPRESSIVE_FRACTURE': 595000,
          'COMPRESSIVE_STRAIN_AT_YIELD': 350,
          'TENSILE_YIELD': 100000,
          'TENSILE_FRACTURE': 170000,
          'TENSILE_STRAIN_AT_YIELD': 120,
          'TORSION_YIELD': 100000,
          'TORSION_FRACTURE': 170000,
          'TORSION_STRAIN_AT_YIELD': 333,
          'SHEAR_YIELD': 100000,
          'SHEAR_FRACTURE': 170000,
          'SHEAR_STRAIN_AT_YIELD': 333,
          'BENDING_YIELD': 100000,
          'BENDING_FRACTURE': 170000,
          'BENDING_ELASTICITY': 120,
          'MAX_EDGE': 10000,
          'STATE_COLOR': {'ALL_SOLID':'WHITE'}
      }
    },
    {
      'name': 'black bronze',
      'advanced': false,
      'usable': true,
      'allow_from_ores': true,
      'constituent_metals': [['copper', 2], ['silver', 1], ['gold', 1]],
      'color_name': 'black2',
      'aesthetic_value': 6,
      'material_properties': {
        	'BUILD_COLOR': '5:6:0',
          'MATERIAL_VALUE': 11,
          'SPEC_HEAT': 385,
          'MELTING_POINT': 11952,
          'BOILING_POINT': 14611,
          'SOLID_DENSITY': 8930,
          'LIQUID_DENSITY': 8020,
          'MOLAR_MASS': 63546,
          'IMPACT_YIELD': 245000,
          'IMPACT_FRACTURE': 770000,
          'IMPACT_STRAIN_AT_YIELD': 175,
          'COMPRESSIVE_YIELD': 245000,
          'COMPRESSIVE_FRACTURE': 770000,
          'COMPRESSIVE_STRAIN_AT_YIELD': 175,
          'TENSILE_YIELD': 70000,
          'TENSILE_FRACTURE': 220000,
          'TENSILE_STRAIN_AT_YIELD': 58,
          'TORSION_YIELD': 70000,
          'TORSION_FRACTURE': 220000,
          'TORSION_STRAIN_AT_YIELD': 145,
          'SHEAR_YIELD': 70000,
          'SHEAR_FRACTURE': 220000,
          'SHEAR_STRAIN_AT_YIELD': 145,
          'BENDING_YIELD': 70000,
          'BENDING_FRACTURE': 220000,
          'BENDING_STRAIN_AT_YIELD': 58,
          'MAX_EDGE': 10000,
          'STATE_COLOR': {'ALL_SOLID':'BLACK'}
      }
    },
    {
      'name': 'rose gold',
      'advanced': false,
      'usable': true,
      'allow_from_ores': true,
      'constituent_metals': [['gold', 3], ['copper', 1]],
      'color_name': 'pink',
      'aesthetic_value': 23,
      'material_properties': {
        	'BUILD_COLOR': '5:5:1',
          'MATERIAL_VALUE': 23,
          'SPEC_HEAT': 129,
          'MELTING_POINT': 11915,
          'BOILING_POINT': 15141,
          'SOLID_DENSITY': 19320,
          'LIQUID_DENSITY': 17310,
          'MOLAR_MASS': 196967,
          'IMPACT_YIELD': 175000,
          'IMPACT_FRACTURE': 350000,
          'IMPACT_STRAIN_AT_YIELD': 97,
          'COMPRESSIVE_YIELD': 175000,
          'COMPRESSIVE_FRACTURE': 350000,
          'COMPRESSIVE_STRAIN_AT_YIELD': 97,
          'TENSILE_YIELD': 50000,
          'TENSILE_FRACTURE': 100000,
          'TENSILE_STRAIN_AT_YIELD': 64,
          'TORSION_YIELD': 50000,
          'TORSION_FRACTURE': 100000,
          'TORSION_STRAIN_AT_YIELD': 185,
          'SHEAR_YIELD': 50000,
          'SHEAR_FRACTURE': 100000,
          'SHEAR_STRAIN_AT_YIELD': 185,
          'BENDING_YIELD': 50000,
          'BENDING_FRACTURE': 100000,
          'BENDING_STRAIN_AT_YIELD': 64,
          'MAX_EDGE': 10000,
          'STATE_COLOR': {'ALL_SOLID':'PINK'}
      }
    },
    {
      'name': 'bismuth',
      'advanced': false,
      'usable': false,
      'allow_from_ores': true,
      'constituent_metals': [],
      'color_name': 'heliotrope',
      'ores': ['Bismuthinite (1)'],
      'aesthetic_value': 2,
      'material_properties': {
        	'BUILD_COLOR': '5:5:1',
          'MATERIAL_VALUE': 2,
          'SPEC_HEAT': 123,
          'MELTING_POINT': 10488,
          'BOILING_POINT': 12815,
          'SOLID_DENSITY': 9780,
          'LIQUID_DENSITY': 10050,
          'MOLAR_MASS': 208980,
          'IMPACT_YIELD': 105000,
          'IMPACT_FRACTURE': 175000,
          'IMPACT_STRAIN_AT_YIELD': 3387,
          'COMPRESSIVE_YIELD': 105000,
          'COMPRESSIVE_FRACTURE': 175000,
          'COMPRESSIVE_STRAIN_AT_YIELD': 3387,
          'TENSILE_YIELD': 30000,
          'TENSILE_FRACTURE': 50000,
          'TENSILE_STRAIN_AT_YIELD': 94,
          'TORSION_YIELD': 30000,
          'TORSION_FRACTURE': 50000,
          'TORSION_STRAIN_AT_YIELD': 250,
          'SHEAR_YIELD': 30000,
          'SHEAR_FRACTURE': 50000,
          'SHEAR_STRAIN_AT_YIELD': 250,
          'BENDING_YIELD': 30000,
          'BENDING_FRACTURE': 50000,
          'BENDING_STRAIN_AT_YIELD': 94,
          'MAX_EDGE': 10000,
          'STATE_COLOR': {'ALL_SOLID':'HELIOTROPE'}
      }
    },
    {
      'name': 'bismuth bronze',
      'advanced': false,
      'usable': true,
      'allow_from_ores': true,
      'constituent_metals': [['tin', 1], ['copper', 2], ['bismuth', 1]],
      'color_name': 'tan',
      'aesthetic_value': 3,
      'material_properties': {
        	'BUILD_COLOR': '6:6:1',
          'MATERIAL_VALUE': 6,
          'SPEC_HEAT': 435,
          'MELTING_POINT': 11868,
          'BOILING_POINT': 14140,
          'SOLID_DENSITY': 8250,
          'LIQUID_DENSITY': 8020,
          'MOLAR_MASS': 80000,
          'IMPACT_YIELD': 602000,
          'IMPACT_FRACTURE': 843500,
          'IMPACT_STRAIN_AT_YIELD': 547,
          'COMPRESSIVE_YIELD': 602000,
          'COMPRESSIVE_FRACTURE': 843500,
          'COMPRESSIVE_STRAIN_AT_YIELD': 547,
          'TENSILE_YIELD': 172000,
          'TENSILE_FRACTURE': 241000,
          'TENSILE_STRAIN_AT_YIELD': 156,
          'TORSION_YIELD': 172000,
          'TORSION_FRACTURE': 241000,
          'TORSION_STRAIN_AT_YIELD': 156,
          'SHEAR_YIELD': 172000,
          'SHEAR_FRACTURE': 241000,
          'SHEAR_STRAIN_AT_YIELD': 156,
          'BENDING_YIELD': 172000,
          'BENDING_FRACTURE': 241000,
          'BENDING_STRAIN_AT_YIELD': 156,
          'MAX_EDGE': 10000,
          'STATE_COLOR': {'ALL_SOLID':'TAN'}
      }
    },
        {
      'name': 'pig iron',
      'advanced': true,
      'usable': false,
      'allow_from_ores': true,
      'constituent_metals': [],
      'color_name': 'gray1',
      'precursor': 'iron',
      'extra_ingredient': 'flux',
      'aesthetic_value': 2,
      'material_properties': {
        	'BUILD_COLOR': '0:7:1',
          'MATERIAL_VALUE': 10,
          'SPEC_HEAT': 500,
          'MELTING_POINT': 12106,
          'BOILING_POINT': 13968,
          'SOLID_DENSITY': 7850,
          'LIQUID_DENSITY': 6980,
          'MOLAR_MASS': 55845,
          'IMPACT_YIELD': 455000,
          'IMPACT_FRACTURE': 700000,
          'IMPACT_STRAIN_AT_YIELD': 268,
          'COMPRESSIVE_YIELD': 455000,
          'COMPRESSIVE_FRACTURE': 700000,
          'COMPRESSIVE_STRAIN_AT_YIELD': 268,
          'TENSILE_YIELD': 130000,
          'TENSILE_FRACTURE': 200000,
          'TENSILE_STRAIN_AT_YIELD': 62,
          'TORSION_YIELD': 130000,
          'TORSION_FRACTURE': 200000,
          'TORSION_STRAIN_AT_YIELD': 159,
          'SHEAR_YIELD': 130000,
          'SHEAR_FRACTURE': 200000,
          'SHEAR_STRAIN_AT_YIELD': 159,
          'BENDING_YIELD': 130000,
          'BENDING_FRACTURE': 200000,
          'BENDING_STRAIN_AT_YIELD': 62,
          'MAX_EDGE': 10000,
          'STATE_COLOR': {'ALL_SOLID':'TAUPE_GRAY'}
      }
    },
    {
      'name': 'steel',
      'advanced': true,
      'usable': true,
      'allow_from_ores': true,
      'constituent_metals': [],
      'color_name': 'gray1',
      'precursor': 'pig iron',
      'extra_ingredient': 'flux',
      'aesthetic_value': 4,
      'material_properties': {
        	'BUILD_COLOR': '0:7:1',
          'MATERIAL_VALUE': 30,
          'SPEC_HEAT': 500,
          'MELTING_POINT': 12718,
          'BOILING_POINT': 14968,
          'SOLID_DENSITY': 7850,
          'LIQUID_DENSITY': 6980,
          'MOLAR_MASS': 55845,
          'IMPACT_YIELD': 1505000,
          'IMPACT_FRACTURE': 2520000,
          'IMPACT_STRAIN_AT_YIELD': 940,
          'COMPRESSIVE_YIELD': 1505000,
          'COMPRESSIVE_FRACTURE': 2520000,
          'COMPRESSIVE_STRAIN_AT_YIELD': 940,
          'TENSILE_YIELD': 430000,
          'TENSILE_FRACTURE': 720000,
          'TENSILE_STRAIN_AT_YIELD': 225,
          'TORSION_YIELD': 430000,
          'TORSION_FRACTURE': 720000,
          'TORSION_STRAIN_AT_YIELD': 215,
          'SHEAR_YIELD': 430000,
          'SHEAR_FRACTURE': 720000,
          'SHEAR_STRAIN_AT_YIELD': 215,
          'BENDING_YIELD': 430000,
          'BENDING_FRACTURE': 720000,
          'BENDING_STRAIN_AT_YIELD': 215,
          'MAX_EDGE': 10000,
          'STATE_COLOR': {'ALL_SOLID':'GRAY'}
      }
    }
  ]
  
  let basic = [];
  let alloy = [];
  let advanced = [];
  let all_metals = [];
  let new_metal;
  
  for (let metal of metals_to_add) {
    if (!metal['advanced'] & (metal['constituent_metals'].length == 0)) {
      new_metal = new Metal(
        metal['name'], metal['advanced'], metal['usable'],
        metal['allow_from_ores'], metal['constituent_metals'], true);
      new_metal.material_properties = metal['material_properties'];
      new_metal.color_name = metal['color_name'];
      new_metal.ores = metal['ores'];
      new_metal.aesthetic_value = metal['aesthetic_value'];
      basic = basic.concat(new_metal);
      all_metals[metal.name] = new_metal
    }
  }
  
  let new_constituents = [];
  for (let metal of metals_to_add) {
    if (!metal['advanced'] & (metal['constituent_metals'].length > 0)) {
      new_constituents = [];
      metal['constituent_metals'].forEach(pair => new_constituents = new_constituents.concat([[all_metals[pair[0]], pair[1]]]));
      new_metal = new Metal(
        metal['name'], metal['advanced'], metal['usable'],
        metal['allow_from_ores'], new_constituents, true);
      new_metal.material_properties = metal['material_properties'];
      new_metal.color_name = metal['color_name'];
      new_metal.aesthetic_value = metal['aesthetic_value'];
      alloy = alloy.concat(new_metal);
      all_metals[metal.name] = new_metal;
    }
  }
  
  for (let metal of metals_to_add) {
    if (metal['advanced']) {
      new_metal = new Metal(
        metal['name'], metal['advanced'], metal['usable'],
        metal['allow_from_ores'], metal['constituent_metals'], true);
      new_metal.material_properties = metal['material_properties'];
      new_metal.color_name = metal['color_name'];
      new_metal.precursor = all_metals[metal.precursor];
      new_metal.extra_ingredient = metal.extra_ingredient;
      new_metal.aesthetic_value = metal['aesthetic_value'];
      advanced = advanced.concat(new_metal);
      all_metals[metal.name] = new_metal;
    }
  }
  return [basic, alloy, advanced];
}

let _vanilla_metals = load_vanilla_metals();
let VANILLA_BASIC = _vanilla_metals[0];
let VANILLA_ALLOYS = _vanilla_metals[1];
let VANILLA_ADVANCED = _vanilla_metals[2];

